/* Pl1ParserTokenManager.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. Pl1ParserTokenManager.java */
package org.bachelor.transpiler.pl1transpiler.parser;
import java.util.ArrayList;
import java.util.HashMap;
import org.bachelor.transpiler.pl1transpiler.symboltable.*;

/** Token Manager. */
@SuppressWarnings ("unused")
public class Pl1ParserTokenManager implements Pl1ParserConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2){
   switch (pos)
   {
      case 0:
         if ((active2 & 0x1000000000L) != 0L)
            return 29;
         if ((active0 & 0xfffffffffffffffeL) != 0L || (active1 & 0xffffffffffffffffL) != 0L || (active2 & 0x3ffffffL) != 0L)
         {
            jjmatchedKind = 172;
            return 33;
         }
         if ((active2 & 0x8000000L) != 0L)
            return 16;
         if ((active2 & 0x40000000L) != 0L)
            return 1;
         if ((active2 & 0x200000000000L) != 0L)
            return 34;
         if ((active2 & 0x20000000L) != 0L)
            return 3;
         if ((active2 & 0x10000000L) != 0L)
            return 13;
         if ((active2 & 0x100000000000000L) != 0L)
            return 35;
         return -1;
      case 1:
         if ((active0 & 0xc0000000000000L) != 0L || (active2 & 0x19900L) != 0L)
            return 33;
         if ((active0 & 0xff3ffffffffffffeL) != 0L || (active1 & 0xffffffffffffffffL) != 0L || (active2 & 0x3fe66ffL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 172;
               jjmatchedPos = 1;
            }
            return 33;
         }
         return -1;
      case 2:
         if ((active0 & 0xc81e6L) != 0L || (active1 & 0xc00000000L) != 0L || (active2 & 0x1L) != 0L)
            return 33;
         if ((active1 & 0x2000000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 172;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0xfffffffffff37e18L) != 0L || (active1 & 0xdffffff3ffffffffL) != 0L || (active2 & 0x3fee6feL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 172;
               jjmatchedPos = 2;
            }
            return 33;
         }
         return -1;
      case 3:
         if ((active0 & 0x18004815818L) != 0L || (active1 & 0xc800048000001828L) != 0L || (active2 & 0x1c20600L) != 0L)
            return 33;
         if ((active1 & 0x2000000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 172;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0xfffffe7ffb7a2664L) != 0L || (active1 & 0x17fffb73ffffe7d7L) != 0L || (active2 & 0x23ce0feL) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 172;
               jjmatchedPos = 3;
            }
            return 33;
         }
         return -1;
      case 4:
         if ((active0 & 0x4020042000600L) != 0L || (active1 & 0x8102040800580L) != 0L || (active2 & 0x22c0086L) != 0L)
            return 33;
         if ((active1 & 0x2000000000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 172;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0xfffbfc7fb97a286cL) != 0L || (active1 & 0x17f7ef53bf7fe277L) != 0L || (active2 & 0x10e078L) != 0L)
         {
            jjmatchedKind = 172;
            jjmatchedPos = 4;
            return 33;
         }
         return -1;
      case 5:
         if ((active0 & 0x2040002228402040L) != 0L || (active1 & 0x1004000025110050L) != 0L || (active2 & 0x6000L) != 0L)
            return 33;
         if ((active0 & 0xdfbbfc5d913a082cL) != 0L || (active1 & 0x7f3ef539a6ee227L) != 0L || (active2 & 0x108078L) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 172;
               jjmatchedPos = 5;
            }
            return 33;
         }
         return -1;
      case 6:
         if ((active0 & 0x8a0ac2c901a0024L) != 0L || (active1 & 0x3110843000c0026L) != 0L || (active2 & 0x100068L) != 0L)
            return 33;
         if ((active0 & 0xd71b505101200808L) != 0L || (active1 & 0x4e2e7109a62e201L) != 0L || (active2 & 0x8010L) != 0L)
         {
            if (jjmatchedPos != 6)
            {
               jjmatchedKind = 172;
               jjmatchedPos = 6;
            }
            return 33;
         }
         return -1;
      case 7:
         if ((active0 & 0x105c0000200000L) != 0L || (active1 & 0x82000080420201L) != 0L || (active2 & 0x8010L) != 0L)
            return 33;
         if ((active0 & 0xd70b005101000808L) != 0L || (active1 & 0x460e7101a20e000L) != 0L)
         {
            jjmatchedKind = 172;
            jjmatchedPos = 7;
            return 33;
         }
         return -1;
      case 8:
         if ((active0 & 0x930a005001000808L) != 0L || (active1 & 0x440811008200000L) != 0L)
            return 33;
         if ((active0 & 0x4401000100000000L) != 0L || (active1 & 0x2066001200e000L) != 0L)
         {
            jjmatchedKind = 172;
            jjmatchedPos = 8;
            return 33;
         }
         return -1;
      case 9:
         if ((active0 & 0x401000100000000L) != 0L || (active1 & 0x200012000000L) != 0L)
            return 33;
         if ((active0 & 0x4000000000000000L) != 0L || (active1 & 0x2046000000e000L) != 0L)
         {
            jjmatchedKind = 172;
            jjmatchedPos = 9;
            return 33;
         }
         return -1;
      case 10:
         if ((active1 & 0x42000000e000L) != 0L)
         {
            jjmatchedKind = 172;
            jjmatchedPos = 10;
            return 33;
         }
         if ((active0 & 0x4000000000000000L) != 0L || (active1 & 0x20040000000000L) != 0L)
            return 33;
         return -1;
      case 11:
         if ((active1 & 0x20000004000L) != 0L)
         {
            jjmatchedKind = 172;
            jjmatchedPos = 11;
            return 33;
         }
         if ((active1 & 0x40000000a000L) != 0L)
            return 33;
         return -1;
      case 12:
         if ((active1 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 172;
            jjmatchedPos = 12;
            return 33;
         }
         if ((active1 & 0x4000L) != 0L)
            return 33;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1, long active2){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 10:
         return jjStartNfaWithStates_0(0, 173, 34);
      case 38:
         return jjStopAtPos(0, 166);
      case 39:
         return jjStartNfaWithStates_0(0, 184, 35);
      case 40:
         return jjStopAtPos(0, 181);
      case 41:
         return jjStopAtPos(0, 182);
      case 42:
         return jjStartNfaWithStates_0(0, 156, 13);
      case 43:
         return jjStopAtPos(0, 159);
      case 44:
         return jjStopAtPos(0, 168);
      case 45:
         return jjStopAtPos(0, 154);
      case 46:
         return jjStopAtPos(0, 183);
      case 47:
         return jjStartNfaWithStates_0(0, 155, 16);
      case 58:
         return jjStopAtPos(0, 180);
      case 60:
         return jjStartNfaWithStates_0(0, 158, 1);
      case 61:
         return jjStopAtPos(0, 163);
      case 62:
         return jjStartNfaWithStates_0(0, 157, 3);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x3c00000800000L, 0x1000000000L, 0x0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0xfc000000000140L, 0x800000000L, 0x1080L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x700000000101800L, 0x800142000000000L, 0x0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x38000000010000a6L, 0x200000000000L, 0x118000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0xc000000002000000L, 0x8000000400000001L, 0x240L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0xc000600L, 0x804000000000L, 0x1000004L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa1_0(0x10000000L, 0x2000000000000002L, 0x0L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa1_0(0x20000000L, 0x4L, 0x0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x4000L, 0x240000000003f8L, 0x800100L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400L, 0x0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0xc0000000L, 0x1000000003800L, 0x20000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000000000L, 0x0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x100000000L, 0x24b000001c000L, 0x0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x600000000L, 0x80000001e0000L, 0x0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x18000c8018L, 0xe00000L, 0x20L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x2000010000L, 0x15d0000001000000L, 0x602018L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x4000402000L, 0x4000000006000000L, 0x1L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x18000000000L, 0x0L, 0xc02L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa1_0(0x20000200000L, 0x38000000L, 0x84000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa1_0(0xc0000020000L, 0xc0000000L, 0x0L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_0(0x300000000000L, 0x200000000000000L, 0x2040000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x300000000L, 0x0L);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x8000000000L);
      case 172:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x1000000000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 61:
         if ((active2 & 0x1000000000L) != 0L)
            return jjStopAtPos(1, 164);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x40c8060020000L, active1, 0x8000080c0200000L, active2, 0x20L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000000L, active1, 0L, active2, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x2L, active1, 0L, active2, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000020000100a4L, active1, 0x15d020000300040eL, active2, 0x60209dL);
      case 70:
      case 102:
         if ((active2 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(1, 136, 33);
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000L, active1, 0L, active2, 0L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x1800L, active1, 0x40000000000L, active2, 0x40400L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x30083000054c0340L, active1, 0x201000800003800L, active2, 0x100002L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000400L, active1, 0L, active2, 0x200L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x100300000000L, active2, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000020002204000L, active1, 0x40004180003f0L, active2, 0x880000L);
      case 79:
      case 111:
         if ((active2 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(1, 139, 33);
         else if ((active2 & 0x10000L) != 0L)
         {
            jjmatchedKind = 144;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x700000988100000L, active1, 0x2002cb600041c000L, active2, 0x28000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x20060000L, active2, 0x4000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x1410800018L, active1, 0x28000000800000L, active2, 0x3000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000L, active1, 0x1000000000L, active2, 0L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000a000L, active1, 0x4000000004000000L, active2, 0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x32000000000000L, active1, 0x180000L, active2, 0L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000000000L, active1, 0x8000000000000001L, active2, 0x40L);
      case 89:
      case 121:
         if ((active2 & 0x1000L) != 0L)
         {
            jjmatchedKind = 140;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0xc0010000000000L, active1, 0L, active2, 0L);
      case 124:
         if ((active2 & 0x8000000000L) != 0L)
            return jjStopAtPos(1, 167);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, active2);
      return 2;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x2000000000000000L, active2, 0L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000010013800L, active1, 0x40008000000L, active2, 0x400000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L, active1, 0x2010000000L, active2, 0L);
      case 67:
      case 99:
         if ((active0 & 0x80L) != 0L)
         {
            jjmatchedKind = 7;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000080080024L, active1, 0x400080001000000L, active2, 0x20L);
      case 68:
      case 100:
         if ((active1 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(2, 98, 33);
         return jjMoveStringLiteralDfa3_0(active0, 0x300400000000L, active1, 0x48400020000010L, active2, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000800000L, active1, 0x80010000000008L, active2, 0x400L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x810000200000000L, active1, 0L, active2, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000400000L, active1, 0L, active2, 0x80L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x20820800004000L, active1, 0x8002008000800020L, active2, 0x2040000L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x800L, active2, 0L);
      case 76:
      case 108:
         if ((active0 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(2, 1, 33);
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L, active1, 0x804000340000000L, active2, 0x8L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000001100000L, active1, 0L, active2, 0L);
      case 78:
      case 110:
         if ((active0 & 0x100L) != 0L)
         {
            jjmatchedKind = 8;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x700400120000040L, active1, 0x20102000000c002L, active2, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x418L, active1, 0x40100000000000c0L, active2, 0x1020000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L, active1, 0x100000000100L, active2, 0x202040L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x2000000L, active2, 0L);
      case 82:
      case 114:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(2, 15, 33);
         return jjMoveStringLiteralDfa3_0(active0, 0x20000c4008020000L, active1, 0x20804084210000L, active2, 0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x5008000200000L, active1, 0x201000401000L, active2, 0x100210L);
      case 84:
      case 116:
         if ((active1 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(2, 99, 33);
         else if ((active2 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(2, 128, 33);
         return jjMoveStringLiteralDfa3_0(active0, 0x2002002000000L, active1, 0x11000000001e2201L, active2, 0x884006L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x4080000000000000L, active1, 0L, active2, 0L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0L, active2, 0x8000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x200L, active1, 0x4L, active2, 0L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x400L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, active2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(1, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, active2);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(3, 23, 33);
         return jjMoveStringLiteralDfa4_0(active0, 0x1080000080000440L, active1, 0x100120204004L, active2, 0L);
      case 67:
      case 99:
         if ((active0 & 0x10L) != 0L)
         {
            jjmatchedKind = 4;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000008L, active1, 0x100220000008000L, active2, 0x4L);
      case 68:
      case 100:
         if ((active2 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 150, 33);
         return jjMoveStringLiteralDfa4_0(active0, 0x140000020000000L, active1, 0L, active2, 0L);
      case 69:
      case 101:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(3, 26, 33);
         else if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 40, 33);
         else if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(3, 67, 33);
         else if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(3, 75, 33);
         else if ((active2 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(3, 137, 33);
         return jjMoveStringLiteralDfa4_0(active0, 0x200c300041000200L, active1, 0x28401004000603L, active2, 0x2018L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000000L, active1, 0x10L, active2, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000L, active1, 0L, active2, 0L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0L, active2, 0x4000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x4801000400200020L, active1, 0x4000080460000L, active2, 0x80080L);
      case 75:
      case 107:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 39, 33);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x1000000000000L, active2, 0x20L);
      case 76:
      case 108:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 16, 33);
         else if ((active1 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 123, 33);
         return jjMoveStringLiteralDfa4_0(active0, 0x8020000000000004L, active1, 0x8000000L, active2, 0x240002L);
      case 77:
      case 109:
         if ((active2 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 152, 33);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L, active1, 0x200880000010000L, active2, 0L);
      case 78:
      case 110:
         if ((active1 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 103, 33);
         else if ((active2 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 138, 33);
         return jjMoveStringLiteralDfa4_0(active0, 0x200000800400000L, active1, 0x2000000800040L, active2, 0x8000L);
      case 79:
      case 111:
         if ((active2 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(3, 151, 33);
         return jjMoveStringLiteralDfa4_0(active0, 0x2420000000000L, active1, 0x2201080000L, active2, 0x40L);
      case 80:
      case 112:
         if ((active1 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 126, 33);
         else if ((active2 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(3, 145, 33);
         return jjMoveStringLiteralDfa4_0(active0, 0x10100000L, active1, 0x100000L, active2, 0x100000L);
      case 82:
      case 114:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x2000800L, active1, 0x10040000000000L, active2, 0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000L, active1, 0L, active2, 0L);
      case 84:
      case 116:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(3, 76, 33);
         else if ((active1 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 127, 33);
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000082000L, active1, 0x2080004000002020L, active2, 0x2000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x6000000000L, active1, 0x1440000052000180L, active2, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L, active1, 0L, active2, 0L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x10000000000L, active2, 0L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa4_0(active0, 0xc0000020000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, active2);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(2, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, active2);
      return 4;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x108000804L, active1, 0x201800084010000L, active2, 0x2028L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x3000104000000000L, active1, 0x40000000000000L, active2, 0L);
      case 68:
      case 100:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 9, 33);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 50, 33);
         else if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 74, 33);
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000000L, active1, 0x30000000000004L, active2, 0L);
      case 69:
      case 101:
         if ((active1 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(4, 94, 33);
         else if ((active2 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(4, 129, 33);
         else if ((active2 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(4, 146, 33);
         else if ((active2 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 153, 33);
         return jjMoveStringLiteralDfa5_0(active0, 0x210000200400008L, active1, 0x10002000000L, active2, 0L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x10000000L, active2, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000200000L, active1, 0x40000000000L, active2, 0L);
      case 72:
      case 104:
         if ((active2 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(4, 130, 33);
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000L, active1, 0x20000000000L, active2, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000c1000022000L, active1, 0x8000020L, active2, 0L);
      case 76:
      case 108:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(4, 30, 33);
         else if ((active1 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 101, 33);
         else if ((active2 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(4, 147, 33);
         return jjMoveStringLiteralDfa5_0(active0, 0x80000020100000L, active1, 0x2000000002040L, active2, 0x100000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000020L, active1, 0x1200200000L, active2, 0L);
      case 78:
      case 110:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 41, 33);
         else if ((active2 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(4, 135, 33);
         return jjMoveStringLiteralDfa5_0(active0, 0x808800401000000L, active1, 0x4000000080000L, active2, 0L);
      case 79:
      case 111:
         if ((active1 & 0x2000000000000000L) != 0L)
            return jjStopAtPos(4, 125);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x100000000068010L, active2, 0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000000L, active1, 0x80000000000L, active2, 0L);
      case 82:
      case 114:
         if ((active1 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 115, 33);
         return jjMoveStringLiteralDfa5_0(active0, 0x4400402000000040L, active1, 0x1480204001000203L, active2, 0x4050L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x400000004000L, active2, 0L);
      case 84:
      case 116:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 10, 33);
         else if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(4, 71, 33);
         else if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 72, 33);
         else if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(4, 87, 33);
         else if ((active1 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 108, 33);
         return jjMoveStringLiteralDfa5_0(active0, 0x20000880000000L, active1, 0x120400000L, active2, 0x8000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000080000L, active1, 0x100000L, active2, 0L);
      case 89:
      case 121:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 25, 33);
         else if ((active2 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 149, 33);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, active2);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(3, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, active2);
      return 5;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000400000020L, active1, 0xc00a4000000020L, active2, 0x100000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x1080000000L, active2, 0L);
      case 67:
      case 99:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 13, 33);
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000000800L, active1, 0x410000000000L, active2, 0L);
      case 68:
      case 100:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(5, 22, 33);
         else if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(5, 88, 33);
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000008L, active1, 0x100000000000000L, active2, 0L);
      case 69:
      case 101:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 29, 33);
         else if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 93, 33);
         else if ((active1 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 114, 33);
         return jjMoveStringLiteralDfa6_0(active0, 0x800800880100000L, active1, 0x10000000202004L, active2, 0L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x10000000L, active2, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x1000008000000L, active2, 0x20L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000L, active1, 0L, active2, 0x8000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x20200010000000L, active1, 0x202200200400002L, active2, 0L);
      case 76:
      case 108:
         if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(5, 80, 33);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x800000080000L, active2, 0L);
      case 77:
      case 109:
         if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 90, 33);
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000L, active1, 0x200L, active2, 0L);
      case 78:
      case 110:
         if ((active1 & 0x1000000000000000L) != 0L)
         {
            jjmatchedKind = 124;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x10c2000220000L, active1, 0x2068001L, active2, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x4400000000000000L, active1, 0L, active2, 0L);
      case 82:
      case 114:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 54, 33);
         else if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(5, 68, 33);
         return jjMoveStringLiteralDfa6_0(active0, 0x1010000100080004L, active1, 0x40000000000L, active2, 0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000001001000000L, active1, 0x400000000004000L, active2, 0x8L);
      case 84:
      case 116:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(5, 27, 33);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 33, 33);
         else if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 61, 33);
         else if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(5, 84, 33);
         else if ((active2 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 141, 33);
         return jjMoveStringLiteralDfa6_0(active0, 0x100004000000000L, active1, 0x100000000L, active2, 0x40L);
      case 85:
      case 117:
         if ((active2 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 142, 33);
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000000L, active1, 0x20000000000000L, active2, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0L, active2, 0x10L);
      case 89:
      case 121:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(5, 6, 33);
         else if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(5, 70, 33);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, active2);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(4, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, active2);
      return 6;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x1500000000000L, active1, 0x40000020201L, active2, 0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x40000000000000L, active2, 0L);
      case 67:
      case 99:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(6, 28, 33);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 45, 33);
         else if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(6, 65, 33);
         else if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(6, 66, 33);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x20000000000000L, active2, 0L);
      case 68:
      case 100:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 47, 33);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 59, 33);
         break;
      case 69:
      case 101:
         if ((active0 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(6, 2, 33);
         else if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(6, 19, 33);
         else if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 55, 33);
         else if ((active1 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 112, 33);
         else if ((active1 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 120, 33);
         else if ((active2 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(6, 131, 33);
         else if ((active2 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(6, 133, 33);
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000200000L, active1, 0x10002000L, active2, 0x10L);
      case 71:
      case 103:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0xc0000000000L, active1, 0L, active2, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x8108001001000000L, active1, 0x400800000004000L, active2, 0L);
      case 76:
      case 108:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(6, 5, 33);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(6, 34, 33);
         else if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(6, 69, 33);
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000000L, active1, 0x1080000000L, active2, 0L);
      case 78:
      case 110:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 53, 33);
         else if ((active1 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 102, 33);
         else if ((active1 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 121, 33);
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000000000000L, active1, 0x82000008008000L, active2, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000000000L, active1, 0x10000400000L, active2, 0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x200000000000L, active2, 0L);
      case 82:
      case 114:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(6, 35, 33);
         else if ((active1 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(6, 96, 33);
         else if ((active1 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 116, 33);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x420000000000L, active2, 0x8000L);
      case 83:
      case 115:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(6, 31, 33);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 37, 33);
         else if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(6, 82, 33);
         else if ((active2 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(6, 134, 33);
         break;
      case 84:
      case 116:
         if ((active1 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(6, 97, 33);
         else if ((active1 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 107, 33);
         return jjMoveStringLiteralDfa7_0(active0, 0x202000000000800L, active1, 0x2200000L, active2, 0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000008L, active1, 0L, active2, 0L);
      case 88:
      case 120:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 20, 33);
         break;
      case 89:
      case 121:
         if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(6, 83, 33);
         else if ((active2 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 148, 33);
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, active2);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(5, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, active2);
      return 7;
   }
   switch(curChar)
   {
      case 52:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 42, 33);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000000L, active1, 0L, active2, 0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000000000L, active1, 0L, active2, 0L);
      case 68:
      case 100:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(7, 21, 33);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 52, 33);
         break;
      case 69:
      case 101:
         if ((active1 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(7, 95, 33);
         else if ((active1 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 113, 33);
         return jjMoveStringLiteralDfa8_0(active0, 0x200000000000800L, active1, 0x801008208000L, active2, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x20000004000L, active2, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000100000000L, active1, 0x20400002000000L, active2, 0L);
      case 76:
      case 108:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 46, 33);
         else if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(7, 64, 33);
         else if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(7, 73, 33);
         else if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(7, 81, 33);
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000000000L, active1, 0x40000000000000L, active2, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000000000000L, active1, 0L, active2, 0L);
      case 78:
      case 110:
         if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(7, 86, 33);
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x2000L, active2, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x100001001000000L, active1, 0L, active2, 0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x50000000000L, active2, 0L);
      case 82:
      case 114:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 44, 33);
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000008L, active1, 0x10000000L, active2, 0L);
      case 83:
      case 115:
         if ((active2 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(7, 132, 33);
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000000000000L, active1, 0L, active2, 0L);
      case 84:
      case 116:
         if ((active1 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 119, 33);
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x200000000000L, active2, 0L);
      case 85:
      case 117:
         if ((active2 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(7, 143, 33);
         break;
      case 86:
      case 118:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000000000L, active1, 0x400000000000000L, active2, 0L);
      case 90:
      case 122:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 43, 33);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, active2);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(6, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x2000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x20000000000000L);
      case 67:
      case 99:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 49, 33);
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x8000L);
      case 68:
      case 100:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 57, 33);
         else if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(8, 91, 33);
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x2000L);
      case 69:
      case 101:
         if ((active0 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(8, 3, 33);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 38, 33);
         else if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 63, 33);
         else if ((active1 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 118, 33);
         else if ((active1 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 122, 33);
         return jjMoveStringLiteralDfa9_0(active0, 0x4400000000000000L, active1, 0x10000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x40000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000000000L, active1, 0L);
      case 78:
      case 110:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(8, 24, 33);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 36, 33);
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 51, 33);
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 56, 33);
         else if ((active1 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 111, 33);
         return jjMoveStringLiteralDfa9_0(active0, 0x100000000L, active1, 0x4000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x200000000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x400000000000L);
      case 82:
      case 114:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(8, 11, 33);
         else if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(8, 85, 33);
         else if ((active1 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 100, 33);
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x20000000000L);
      case 83:
      case 115:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 60, 33);
         else if ((active1 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 104, 33);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x20000004000L);
      case 68:
      case 100:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 58, 33);
         else if ((active1 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(9, 92, 33);
         break;
      case 69:
      case 101:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 48, 33);
         break;
      case 71:
      case 103:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(9, 32, 33);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x40000002000L);
      case 76:
      case 108:
         if ((active1 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(9, 89, 33);
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x20000000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000000000000000L, active1, 0L);
      case 82:
      case 114:
         if ((active1 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 109, 33);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x400000008000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x2000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x4000L);
      case 67:
      case 99:
         if ((active1 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 106, 33);
         break;
      case 69:
      case 101:
         if ((active1 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 117, 33);
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x8000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x400000000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x20000000000L);
      case 84:
      case 116:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 62, 33);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(9, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, 0L, active1, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(11, 79, 33);
         break;
      case 72:
      case 104:
         return jjMoveStringLiteralDfa12_0(active1, 0x20000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa12_0(active1, 0x4000L);
      case 78:
      case 110:
         if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(11, 77, 33);
         break;
      case 82:
      case 114:
         if ((active1 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 110, 33);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa12_0(long old1, long active1){
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(10, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, 0L, active1, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(12, 78, 33);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa13_0(active1, 0x20000000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa13_0(long old1, long active1){
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(11, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, 0L, active1, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         if ((active1 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(13, 105, 33);
         break;
      default :
         break;
   }
   return jjStartNfa_0(12, 0L, active1, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec1 = {
   0x0L, 0x0L, 0x100000000000L, 0x0L
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 33;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 33:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 172)
                        kind = 172;
                     { jjCheckNAddTwoStates(9, 10); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAddTwoStates(10, 11); }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 172)
                        kind = 172;
                     { jjCheckNAddTwoStates(9, 10); }
                  }
                  else if ((0x100003200L & l) != 0L)
                  {
                     if (kind > 178)
                        kind = 178;
                     { jjCheckNAddStates(0, 2); }
                  }
                  else if (curChar == 10)
                  {
                     if (kind > 178)
                        kind = 178;
                     { jjCheckNAddTwoStates(27, 26); }
                  }
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 16;
                  else if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 13;
                  else if (curChar == 39)
                     { jjCheckNAddTwoStates(7, 8); }
                  else if (curChar == 62)
                     jjstateSet[jjnewStateCnt++] = 3;
                  else if (curChar == 60)
                     jjstateSet[jjnewStateCnt++] = 1;
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 170)
                        kind = 170;
                     { jjCheckNAdd(5); }
                  }
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 174)
                        kind = 174;
                  }
                  if (curChar == 57)
                  {
                     if (kind > 169)
                        kind = 169;
                     { jjCheckNAdd(4); }
                  }
                  break;
               case 34:
                  if ((0x100003200L & l) != 0L)
                  {
                     if (kind > 178)
                        kind = 178;
                     { jjCheckNAddTwoStates(27, 26); }
                  }
                  else if (curChar == 10)
                  {
                     if (kind > 178)
                        kind = 178;
                     { jjCheckNAddTwoStates(27, 26); }
                  }
                  break;
               case 29:
                  if (curChar == 62)
                  {
                     if (kind > 165)
                        kind = 165;
                  }
                  else if (curChar == 60)
                  {
                     if (kind > 160)
                        kind = 160;
                  }
                  break;
               case 35:
                  if ((0x3ff030300000000L & l) != 0L)
                     { jjCheckNAddTwoStates(7, 8); }
                  else if (curChar == 39)
                  {
                     if (kind > 171)
                        kind = 171;
                  }
                  break;
               case 1:
                  if (curChar == 61 && kind > 161)
                     kind = 161;
                  break;
               case 2:
                  if (curChar == 62)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
                  if (curChar == 61 && kind > 162)
                     kind = 162;
                  break;
               case 4:
                  if (curChar != 57)
                     break;
                  if (kind > 169)
                     kind = 169;
                  { jjCheckNAdd(4); }
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 170)
                     kind = 170;
                  { jjCheckNAdd(5); }
                  break;
               case 6:
                  if (curChar == 39)
                     { jjCheckNAddTwoStates(7, 8); }
                  break;
               case 7:
                  if ((0x3ff030300000000L & l) != 0L)
                     { jjCheckNAddTwoStates(7, 8); }
                  break;
               case 8:
                  if (curChar == 39 && kind > 171)
                     kind = 171;
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 172)
                     kind = 172;
                  { jjCheckNAddTwoStates(9, 10); }
                  break;
               case 10:
                  if (curChar == 45)
                     { jjCheckNAddTwoStates(10, 11); }
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 172)
                     kind = 172;
                  { jjCheckNAddTwoStates(10, 11); }
                  break;
               case 12:
                  if ((0x3fe000000000000L & l) != 0L && kind > 174)
                     kind = 174;
                  break;
               case 14:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 175)
                     kind = 175;
                  jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 15:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 16:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 17:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 18:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 19:
                  if (curChar == 39)
                     { jjCheckNAddTwoStates(20, 21); }
                  break;
               case 20:
                  if ((0x3ff030300000000L & l) != 0L)
                     { jjCheckNAddTwoStates(20, 21); }
                  break;
               case 21:
                  if (curChar == 39)
                     { jjCheckNAddTwoStates(22, 24); }
                  break;
               case 22:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(22, 24); }
                  break;
               case 23:
                  if (curChar == 47 && kind > 176)
                     kind = 176;
                  break;
               case 24:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 26:
                  if (curChar != 10)
                     break;
                  if (kind > 178)
                     kind = 178;
                  { jjCheckNAddTwoStates(27, 26); }
                  break;
               case 27:
                  if ((0x100003200L & l) == 0L)
                     break;
                  if (kind > 178)
                     kind = 178;
                  { jjCheckNAddTwoStates(27, 26); }
                  break;
               case 30:
                  if (curChar == 62 && kind > 165)
                     kind = 165;
                  break;
               case 31:
                  if ((0x100003200L & l) == 0L)
                     break;
                  if (kind > 178)
                     kind = 178;
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 32:
                  if ((0x100003200L & l) == 0L)
                     break;
                  if (kind > 179)
                     kind = 179;
                  { jjCheckNAdd(32); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 33:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 172)
                        kind = 172;
                     { jjCheckNAddTwoStates(9, 10); }
                  }
                  else if (curChar == 95)
                     { jjCheckNAddTwoStates(10, 11); }
                  break;
               case 0:
               case 9:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 172)
                     kind = 172;
                  { jjCheckNAddTwoStates(9, 10); }
                  break;
               case 35:
               case 7:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(7, 8); }
                  break;
               case 10:
                  if (curChar == 95)
                     { jjCheckNAddTwoStates(10, 11); }
                  break;
               case 11:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 172)
                     kind = 172;
                  { jjCheckNAddTwoStates(10, 11); }
                  break;
               case 13:
                  if (curChar != 124)
                     break;
                  if (kind > 175)
                     kind = 175;
                  { jjCheckNAdd(14); }
                  break;
               case 14:
                  if (kind > 175)
                     kind = 175;
                  { jjCheckNAdd(14); }
                  break;
               case 17:
                  { jjAddStates(3, 4); }
                  break;
               case 20:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjAddStates(5, 6); }
                  break;
               case 22:
                  { jjAddStates(7, 8); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((jjbitVec1[i2] & l2) != 0L)
                     { jjAddStates(9, 10); }
                  break;
               case 14:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 175)
                     kind = 175;
                  jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 17:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(3, 4); }
                  break;
               case 22:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(7, 8); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 33 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, "\55", "\57", "\52", "\76", "\74", "\53", null, null, null, "\75", "\254\75", 
null, "\46", "\174\174", "\54", null, null, null, null, "\12", null, null, null, 
null, null, null, "\72", "\50", "\51", "\56", "\47", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   27, 26, 32, 17, 18, 20, 21, 22, 24, 29, 30, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 59 && (0x800000000000000L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public Pl1ParserTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public Pl1ParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 33; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0x1f0ffffffffffffL, 
};
static final long[] jjtoSkip = {
   0x0L, 0x0L, 0xf000000000000L, 
};
static final long[] jjtoSpecial = {
   0x0L, 0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[33];
    private final int[] jjstateSet = new int[2 * 33];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
