/* Generated By:JavaCC: Do not edit this line. Pl1ParserTreeConstants.java Version 7.0.12 */
package org.bachelor.transpiler.pl1transpiler.parser;

public interface Pl1ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTPACKAGE = 1;
  public int JJTGLOBAL = 2;
  public int JJTCONDITION = 3;
  public int JJTPROC = 4;
  public int JJTHEAD = 5;
  public int JJTBODY = 6;
  public int JJTENTRY = 7;
  public int JJTRETURNS = 8;
  public int JJTOPTIONS = 9;
  public int JJTCALLS = 10;
  public int JJTFETCH = 11;
  public int JJTSTATEMENT = 12;
  public int JJTRELEASE = 13;
  public int JJTTERMINATE = 14;
  public int JJTRETURN_VAL = 15;
  public int JJTPARA = 16;
  public int JJTVAR = 17;
  public int JJTMINOR = 18;
  public int JJTHIERACHIE = 19;
  public int JJTTYPE = 20;
  public int JJTFILE = 21;
  public int JJTSTREAM = 22;
  public int JJTRECORD = 23;
  public int JJTINPUT = 24;
  public int JJTOUTPUT = 25;
  public int JJTUPDATE = 26;
  public int JJTSEQUENTIAL = 27;
  public int JJTDIRECT = 28;
  public int JJTBUFFERED = 29;
  public int JJTUNBUFFERED = 30;
  public int JJTPICTUREEXPRESSION = 31;
  public int JJTPICTURE = 32;
  public int JJTWIDEPIC = 33;
  public int JJTPICTUREATTRIBUTE = 34;
  public int JJTPICTURELETTER = 35;
  public int JJTNUMBER = 36;
  public int JJTPICTURELENGTH = 37;
  public int JJTLOCATOR = 38;
  public int JJTPOINTER = 39;
  public int JJTOFFSET = 40;
  public int JJTHANDLE = 41;
  public int JJTSTRING = 42;
  public int JJTWIDECHAR = 43;
  public int JJTGRAPHIC = 44;
  public int JJTCHAR = 45;
  public int JJTBIT = 46;
  public int JJTARITHMETIC = 47;
  public int JJTSIGNED = 48;
  public int JJTUNSIGNED = 49;
  public int JJTDECIMAL = 50;
  public int JJTFIXED = 51;
  public int JJTFLOAT = 52;
  public int JJTBINARY = 53;
  public int JJTSIZE = 54;
  public int JJTLENGTH = 55;
  public int JJTINT = 56;
  public int JJTDOUBLE = 57;
  public int JJTREAL = 58;
  public int JJTCOMPLEX = 59;
  public int JJTID = 60;


  public String[] jjtNodeName = {
    "PROGRAM",
    "PACKAGE",
    "GLOBAL",
    "CONDITION",
    "PROC",
    "HEAD",
    "BODY",
    "ENTRY",
    "RETURNS",
    "OPTIONS",
    "CALLS",
    "FETCH",
    "STATEMENT",
    "RELEASE",
    "TERMINATE",
    "return_val",
    "PARA",
    "VAR",
    "MINOR",
    "HIERACHIE",
    "TYPE",
    "File",
    "Stream",
    "Record",
    "Input",
    "Output",
    "Update",
    "Sequential",
    "Direct",
    "Buffered",
    "Unbuffered",
    "PictureExpression",
    "Picture",
    "Widepic",
    "PictureAttribute",
    "PictureLetter",
    "Number",
    "PictureLength",
    "Locator",
    "Pointer",
    "Offset",
    "Handle",
    "String",
    "Widechar",
    "Graphic",
    "Char",
    "Bit",
    "Arithmetic",
    "Signed",
    "Unsigned",
    "Decimal",
    "Fixed",
    "Float",
    "Binary",
    "size",
    "Length",
    "Int",
    "Double",
    "Real",
    "Complex",
    "Id",
  };
}
/* JavaCC - OriginalChecksum=2f35b93db02f2082f7920cba4091d37a (do not edit this line) */
