/* Generated By:JavaCC: Do not edit this line. Pl1ParserTreeConstants.java Version 7.0.12 */
package org.bachelor.transpiler.pl1transpiler.parser;

public interface Pl1ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTPACKAGE = 1;
  public int JJTEND = 2;
  public int JJTPROC = 3;
  public int JJTHEAD = 4;
  public int JJTBODY = 5;
  public int JJTBRANCH = 6;
  public int JJTLOOP = 7;
  public int JJTUNTIL = 8;
  public int JJTSPECIFICATION = 9;
  public int JJTBOOL = 10;
  public int JJTOP = 11;
  public int JJTENTRY = 12;
  public int JJTDISPLAY = 13;
  public int JJTASSIGN = 14;
  public int JJTCALC = 15;
  public int JJTRETURNS = 16;
  public int JJTOPTIONS = 17;
  public int JJTCALLS = 18;
  public int JJTREAD_FILE = 19;
  public int JJTWRITE_FILE = 20;
  public int JJTSTRINGLIST = 21;
  public int JJTFETCH = 22;
  public int JJTSTATEMENT = 23;
  public int JJTRELEASE = 24;
  public int JJTTERMINATE = 25;
  public int JJTPARA = 26;
  public int JJTVAR = 27;
  public int JJTMINOR = 28;
  public int JJTTYPE = 29;
  public int JJTFILE = 30;
  public int JJTPICTUREEXPRESSION = 31;
  public int JJTSTRING = 32;
  public int JJTARITHMETIC = 33;
  public int JJTID = 34;


  public String[] jjtNodeName = {
    "PROGRAM",
    "PACKAGE",
    "END",
    "PROC",
    "HEAD",
    "BODY",
    "BRANCH",
    "LOOP",
    "UNTIL",
    "specification",
    "BOOL",
    "OP",
    "ENTRY",
    "DISPLAY",
    "ASSIGN",
    "CALC",
    "RETURNS",
    "OPTIONS",
    "CALLS",
    "READ_FILE",
    "WRITE_FILE",
    "STRINGLIST",
    "FETCH",
    "STATEMENT",
    "RELEASE",
    "TERMINATE",
    "PARA",
    "VAR",
    "MINOR",
    "TYPE",
    "File",
    "PictureExpression",
    "String",
    "Arithmetic",
    "Id",
  };
}
/* JavaCC - OriginalChecksum=abd465af1c5949a7dc4e8f8af46e33ab (do not edit this line) */
